### Create publisher
POST http://localhost:8080/api/publishers
Content-Type: application/json

{
  "name": "name",
  "vat": "1234567-9"
}

### List publishers
GET http://localhost:8080/api/publishers
Content-Type: application/json

###